### ISSUE TITLE
Face area computation failing with quad hexagon mesh

### ISSUE THREAD

**Issue by philipc2** [UXARRAY/uxarray#835]
Running `uxgrid.face_areas` failes for the `quad-hexagon` mesh located in `test\meshfiles\ugrid\quad-hexagon\grid.nc`

### Traceback 
```



---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Cell In[30], line 1
----> 1 uxgrid.face_areas

File ~\PycharmProjects\uxarray\uxarray\uxarray\grid\grid.py:859, in Grid.face_areas(self)
    856 from uxarray.conventions.descriptors import FACE_AREAS_DIMS, FACE_AREAS_ATTRS
    858 if "face_areas" not in self._ds:
--> 859     face_areas, self._face_jacobian = self.compute_face_areas()
    860     self._ds["face_areas"] = xr.DataArray(
    861         data=face_areas, dims=FACE_AREAS_DIMS, attrs=FACE_AREAS_ATTRS
    862     )
    863 return self._ds["face_areas"]

File ~\PycharmProjects\uxarray\uxarray\uxarray\grid\grid.py:1119, in Grid.compute_face_areas(self, quadrature_rule, order, latlon)
   1116 n_nodes_per_face = self.n_nodes_per_face.values
   1118 # call function to get area of all the faces as a np array
-> 1119 self._face_areas, self._face_jacobian = get_all_face_area_from_coords(
   1120     x,
   1121     y,
   1122     z,
   1123     face_nodes,
   1124     n_nodes_per_face,
   1125     dim,
   1126     quadrature_rule,
   1127     order,
   1128     coords_type,
   1129 )
   1131 min_jacobian = np.min(self._face_jacobian)
   1132 max_jacobian = np.max(self._face_jacobian)

File ~\anaconda3\envs\uxarray_build\Lib\site-packages\numba\core\dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File ~\anaconda3\envs\uxarray_build\Lib\site-packages\numba\core\dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'node3.3', defined at C:\Users\chmie\PycharmProjects\uxarray\uxarray\uxarray\grid\area.py (81)

File "uxarray\uxarray\grid\area.py", line 81:
def calculate_face_area(
    <source elided>
            if quadrature_rule == "gaussian":
                for q in range(len(dW)):
                ^

During: typing of assignment at C:\Users\chmie\PycharmProjects\uxarray\uxarray\uxarray\grid\area.py (81)

File "uxarray\uxarray\grid\area.py", line 81:
def calculate_face_area(
    <source elided>
            if quadrature_rule == "gaussian":
                for q in range(len(dW)):
                ^

During: resolving callee type: type(CPUDispatcher(<function calculate_face_area at 0x000001A227B72340>))
During: typing of call at C:\Users\chmie\PycharmProjects\uxarray\uxarray\uxarray\grid\area.py (166)

During: resolving callee type: type(CPUDispatcher(<function calculate_face_area at 0x000001A227B72340>))
During: typing of call at C:\Users\chmie\PycharmProjects\uxarray\uxarray\uxarray\grid\area.py (166)


File "uxarray\uxarray\grid\area.py", line 166:
def get_all_face_area_from_coords(
    <source elided>
        # After getting all the nodes of a face assembled call the  cal. face area routine
        face_area, face_jacobian = calculate_face_area(
```

**Comment by philipc2** [comment]
@rajeeja 

Any idea on why this could be happening? It works fine with most of the other meshes I've been working with.

**Comment by rajeeja** [comment]
Will take a look and get back lat r today

**Comment by rajeeja** [comment]
> @rajeeja
> 
> Any idea on why this could be happening? It works fine with most of the other meshes I've been working with.

I was able to replicate, seems like type mismatch between array(float32, 1d, C) and array(float64, 1d, C) in the calculate_face_area function.  checking the various items loaded after 

`ux.open_grid("./test/meshfiles/ugrid/quad-hexagon/grid.nc")`

**Comment by philipc2** [comment]
Yeah, this looks like the case. Looking at the data types of the `quax-hexagon` grid, the coordinates are `float32`

![image](https://github.com/UXARRAY/uxarray/assets/67855069/f7281833-e653-4cdc-be33-8ede74377166)

Maybe changing this:

https://github.com/UXARRAY/uxarray/blob/b0e065139b0a8433d0794e8b7f4fd52c63254b90/uxarray/grid/area.py#L64-L67

To the following

```Python
     node1 = np.array([x[0], y[0], z[0]], dtype=x.dtype) 
     node2 = np.array([x[j + 1], y[j + 1], z[j + 1]], dtype=x.dtype) 
     node3 = np.array([x[j + 2], y[j + 2], z[j + 2]], dtype=x.dtype)

**Comment by philipc2** [comment]
Just tried the changes above locally and it works for me.

**Comment by rajeeja** [comment]
When I do, it says float32, 

```
a.face_x.values

Out[19]: array([0.99286216, 0.9877206 , 0.97738284, 0.96628404], dtype=float32)
```
we should have everthing internally set to float64 or maybe when calling functions with `numba` decorators, we can check and convert things that are float32 to float64 before doing anything, a small `function` (see below) to test it might be one solution
```
def convert_to_float64(*arrays):
  return [np.asarray(arr, dtype=np.float64) for arr in arrays]
```

**Comment by philipc2** [comment]
I'm not opposed to it, but I don't see a need to have everything be explicitly set to `float64`. If our coordinates come as `float32` (as is the case with the `quad-hexagon` grid, we would need to convert everything to `float64`). 

The code snipped I provided uses the datatype of the inputted coordinates instead of assuming that it is `float64`.

**Comment by philipc2** [comment]
With the `dtype=x.dtype` change, I was able to successfully generate the face areas.

![image](https://github.com/UXARRAY/uxarray/assets/67855069/5d569c96-4ec8-453a-b5e8-5e8ae2c4f0e9)
